export const TOGGLE_MODAL_PLUS = 'TOGGLE_MODAL_PLUS'

// Users

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'
export const ADD_USERS = 'ADD_USERS'
export const DELETE_USER = 'DELETE_USER'
